### PR TITLE
Fix for labels in radiobuttons toggle.

### PR DESCRIPTION
**Pull request by rwz**
Rails generates different ids for radiobuttons elements depending on the radiobutton value. It breaks you implementation where label `for` attribute is `#{model_name}_#{attribute_name}`.

I've made a stupid quick fix that removes `for` from radiobuttons at all, cause it's not needed on wrapping labels with just one input tab inside.

### CODE REVIEW

**Comment by stouset** [comment]
Also, what happened to the other pull request? :)

**Comment by rwz** [comment]
I've removed it cause it was breaking checkboxes :)

**Comment by stouset** [comment]
I made this comment on the other request, but repeating it here because the other isn't visible any more. :) Why not leave the `for` attribute on labels around radio buttons? Does it break anything?

**Comment by rwz** [comment]
Cause it's not working. Your current master:

```
= user.toggles 'Gender' do
  = user.radiobutton :gender, 'Male', :male
  = user.radiobutton :gender, 'Female', :female
```

html:

```
<li>
<label for="user_gender">
    <input id="user_gender_male" name="user[gender]" type="radio" value="male">
    <span>Male</span>
</label>
</li>
<li>
<label for="user_gender">
    <input id="user_gender_female" name="user[gender]" type="radio" value="female">
    <span>Female</span>
</label>
</li>
```

Label `for` attribute does not match radiobutton's `id`, so clicking label area does not toggle input.

**Comment by stouset** [comment]
Ooh. Good catch. I'll merge this in tomorrow.

**Comment by stouset** [comment]
Merged. A release will go out once I make sure there's support for Bootstrap 1.4.0.

**Comment by stouset** [comment]
1.0.3 has been released with this fix included.

**Comment by rwz** [comment]
Awesome.

**Pull request merged**
