### PR TITLE
disables field_error_proc for all bootstap generated code

### PR DESCRIPTION
**Pull request by rwz**
This patch disables default field_error_proc for all code `twitter_bootstrap_form_for` generates cause before it was breaking bootstrap's layout by wrapping input and label with `div.field_with_error`

before:
http://dl.dropbox.com/u/8663332/twitter_bootstrap_form_for/before.png

after:
http://dl.dropbox.com/u/8663332/twitter_bootstrap_form_for/after.png

### CODE REVIEW

**Comment by stouset** [comment]
Out of curiosity, were you able to determine why this wasn't working for you before?

**Comment by stouset** [comment]
Oh, I see. In your original bug report, you hadn't wrapped the field with a fieldset using `inputs`. Can I ask why?

**Comment by stouset** [comment]
Pulled. I actually moved this bit of code out into the main `twitter_bootstrap_form_for` wrapper, so it should only ever need to be called once per form. I've tested this (with and without an `inputs` wrapper), but can you ensure that it works for you before I release?

609807a029e62cb03d69d4bb356a58b3abc3d31c

**Comment by derekprior** [comment]
I can confirm that this resolves #23

**Comment by stouset** [comment]
Great. I'll push out a release soon. Have a few more issues that should probably make it in.

**Comment by rwz** [comment]
Yeah, works for me too.

**Pull request merged**
