### PR TITLE
Remove Haml dependency, fixes #3

### LINKED ISSUE #3: Remove dependency on Haml
It's probably too onerous to require other people use Haml. We should see if it's faster to use ERB partials or simply render the HTML ourselves in code.

### PR DESCRIPTION
**Pull request by zzip**
Haml templates are rewritten in code. Haml dependency is removed

This also fixes a problem i had when using `inputs` and `actions` in an erb template.

### CODE REVIEW

**Comment by stouset** [comment]
I made some nitpicky style tweaks and fixed a minor rendering bug, then merged it. Thanks!

**Comment by stouset** [comment]
I've pushed a new prerelease (`1.0.0.rc2`) to rubygems with your fix and another one. Let me know if you experience any issues with this build. If not, I'll go ahead and release 1.0.0 into the wild.

**Comment by zzip** [comment]
Works fine here with the latest changes, good the field_with_errors div is also fixed.

**Comment by stouset** [comment]
I'll go ahead and push 1.0 then. I'm not currently using inline fields, so I'm just going to release with what's available and implement them when someone (perhaps me) needs them.

**Pull request merged**
