### PR TITLE
Upgrade to Rails 4 and Bootstrap 3

### PR DESCRIPTION
**Pull request by apfritts**

### CODE REVIEW

**Comment by apfritts** [comment]
Note: I've added a few bug fixes post requesting a pull. The latest would be the best!

**Comment by caarlos0** [comment]
How do you fix the inline checkboxes issue?

**Comment by stouset** [comment]
@apfritts Sorry to take so long to respond. I've been away on vacation.

I'm happy to merge this, but honestly, I haven't used this project myself in years. Testing it is difficult for me since I have nothing really set up any more to ensure it works, and I'm looking to hand it over to someone else to maintain. Do you have any interest?

**Comment by apfritts** [comment]
Hi Stephen! No problem. I'm fine with taking over maintanence on this
project. Not quite sure how we do that.

On Tuesday, September 3, 2013, Stephen Touset wrote:

> @apfritts https://github.com/apfritts Sorry to take so long to respond.
> I've been away on vacation.
> 
> I'm happy to merge this, but honestly, I haven't used this project myself
> in years. Testing it is difficult for me since I have nothing really set up
> any more to ensure it works, and I'm looking to hand it over to someone
> else to maintain. Do you have any interest?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stouset/twitter_bootstrap_form_for/pull/84#issuecomment-23737382
> .

## 

0b100110110001011110101111011110001

There are only 10 types of people in the world: those who understand
binary, and those who don't.

**Comment by apfritts** [comment]
Hi Stephen!

Let me know when you're available to transfer ownership of the repo. I'll
need to nuke my fork I think.
https://help.github.com/articles/how-to-transfer-a-repository

0b100110110001011110101111011110001

There are only 10 types of people in the world: those who understand
binary, and those who don't.

**Comment by DavidAllison** [comment]
@stouset @apfritts Any update on this?

**Pull request merged**
