### PR TITLE
Bootstrap 2.0 compatibility changes

### PR DESCRIPTION
**Pull request by beeandbo**
I'm not sure you should pull this directly, but it includes a lot of small tweaks to add bootstrap 2.0 compatibility.  I haven't done extensive testing.  I've just been making sure everything works on my own forms.

Hopefully this can at least serve as a guide for a few of the changes you need to make.

Keith

### CODE REVIEW

**Comment by qzio** [comment]
I'm using this and it works for me; big thanks!

**Comment by kirs** [comment]
:+1: Thanks!

**Comment by megalithic** [comment]
i'm curious of which rails and/or twitter bootstrap plugins/assets you all are using.. i'm using bootstrap-sass-rails along with tzeskimo's branch of twitter_bootstrap_form_for. however, i'm not able to replicate the sample "no extra css needed" example of a form built with t_b_f_f.

any help/suggestions? was going to turn to posting up on stackoverflow next.

**Comment by beeandbo** [comment]
If you're just doing a few plain forms without all the extra bootstrap markup, I'd suggest just using the plain old rails form builders.  If this is going to be your common case, you might want to check out a more flexible form builder like simple_form.  It looks like it even has bootstrap support.

**Pull request closed without merging**
